import React from 'react';

function Rgpd() {

    return (
        <div className='game-rules'>
            <h1>CONDITIONS GENERALES D'UTILISATION</h1>

            <p>Est dénommé ci-après "l'organisateur", l'entité commerciale qui propose le jeu à ses visiteurs et en définit les règlements.</p>
            <p>Est dénommée ci-après "la plate-forme", l'entreprise détentrice du jeu et de l'application mobile qui met à disposition le jeu pour une période et une localisation définies.</p>
           
            <h4>1.Inscription</h4>
            <p>L'inscription d'un joueur majeur est requis pour utiliser la plate-forme. Cette inscription s'effectue via une connexion Internet sur un smartphone permettant la lecture des QR Codes. Les champs d'informations relatifs à la création du compte sont standardisés par la plate-forme. L'organisateur peut toutefois compléter ces demandes d'informations de façon spécifique à un évènement. L'ensemble des champs sont requis pour l'accès à la plate-forme de jeu.

                Il reste de la complète responsabilité de l'utilisateur de saisir des informations complètes et correctes. Toute erreur volontaire ou involontaire dans la saisie des informations du joueur pourra entraîner l'exclusion du joueur à la plate-forme ou l'impossibilité pour l'organisateur de délivrer une récompense selon les règlements du jeu.

                En outre, l'organisateur ou la plate-forme ne pourront pas être tenus pour responsables de l'impossibilité de joindre un joueur dans le cas où les informations saisies ne permettraient pas une mise en relation simple et rapide. Les conditions de mises en relation pourront être définies de façon précise à chaque évènement dans les règlements du jeu.
            </p>

            <h4>2.Participation au jeu</h4>
            <p>L'utilisateur participe au jeu en toute bonne foi. Il effectuera sa participation sans tenter de frauder le principe du jeu et conformément au règlements du jeu.</p>
            <h4>3.Compte et jeux multiples</h4>
            <p>La création d'un compte à la plate-forme est unifié pour tous les évènements développés par celle-ci, quels que soient les organisateurs. Toutefois, chaque jeu ou évènement reste totalement indépendant et soumis au règlement édité pour celui-ci.</p>


            <h2>POLITIQUE DE CONFIDENTIALITÉ ET POLITIQUE RELATIVE AUX COOKIES</h2>

            <p>Cette Politique de confidentialité et relative aux cookies établit les conditions générales sous lesquelles AMOMENTI, dont le siège est 2 Grand'Rue, 79700 Mauléon, responsable du traitement des données aux fins de la politique de confidentialité et relatives aux cookies (ci-après, conjointement « nous » ou les « responsables du traitement »), traite les données personnelles que vous nous fournissez en utilisant l'application mobile de jeu (ci-après le « site Internet ») ou l'application mobile, à savoir l'application informatique destinée à être utilisée sur smartphones, tablettes ou autres appareils mobiles (ci-après, l'«Application») ou d'autres applications, logiciels, médias numériques, moyens de stockage ou fonctionnalités liées à la marque commerciale de la société en France (ci-après conjointement, la « Plateforme »).
                En utilisant la Plateforme, chaque fois que vous nous fournissez ou que nous sommes obligés d'accéder à tout type d'informations qui, en raison des caractéristiques de ces dernières, nous permettent de vous identifier, à savoir potentiellement et sans exhaustivité : vos prénom, nom, adresse e-mail, adresses, numéro de téléphone, type d'appareil (ci-après, « Données personnelles »), que ce soit à des fins de navigation, de participation à l'expérience de jeu mobile ou d'achat de nos produits ou d'utilisation de nos services ou fonctionnalités, vous serez soumis à la Politique de confidentialité et relative aux Cookies, aux Conditions générales d'achat et d'utilisation, ainsi qu'aux autres documents cités aux présentes (ci-après conjointement, les « Conditions générales »), qui s'appliquent à tout moment et doivent être consultées pour vous assurer que vous les acceptez.</p>

            <h4>1. Collecte des données personnelles et finalités de traitement</h4>
            <p>Sachez qu'avant d'utiliser l'un de nos services ou l'une de nos fonctionnalités vous devez lire cette politique de confidentialité et relative aux Cookies, ainsi que la section spécifique des conditions générales sur le service ou la fonctionnalité concernée. Dans chaque section, vous pourrez voir s'il existe des conditions d'utilisation spécifiques, ou si un traitement spécifique de vos données personnelles est nécessaire.
                Ne pas fournir certaines informations obligatoires peut empêcher votre inscription en tant qu'utilisateur ou l'utilisation de certaines fonctionnalités ou de certains services disponibles via la plateforme.
                L'utilisateur (vous) assure par la présente que les données personnelles fournies sont véridiques et exactes, tout en acceptant de communiquer tout changement ou modification à cet égard. Si vous nous fournissez les données personnelles de tiers, vous serez responsable de les informer et d'obtenir leur accord concernant la transmission de ces informations aux fins indiquées dans les sections correspondantes de cette politique de confidentialité et relative aux Cookies. Toute perte ou tout dommage causé à la Plateforme, aux responsables du traitement ou à tout tiers suite à la communication d'informations erronées, inexactes ou incomplètes sur les formulaires d'inscription relèvera uniquement de la responsabilité de l'utilisateur.
                Les responsables du traitement, selon le cas, utiliseront les données personnelles aux fins suivantes :</p>

            <h5>1.1 Gérer votre inscription en tant qu'utilisateur de la plateforme. Les données personnelles que vous nous fournissez seront utilisées afin de vous identifier en tant qu'utilisateur de la plateforme et vous donner accès aux différents produits, services et fonctionnalités qui pourraient être disponibles pour les utilisateurs enregistrés.</h5>
            <h5>1.2 Vous contacter par e-mail, téléphone, SMS ou autres formes équivalentes de communication électronique, telles que des « push notifications » de l'application, etc. concernant des mises à jour ou des messages d'information sur les fonctionnalités, produits ou services souscrits, y compris des mises à jour de sécurité de la plateforme, si leur installation s'avère nécessaire ou recommandée.</h5>
            <h5>1.3 Traiter et gérer vos demandes formulées en utilisant les moyens de contact du service clientèle disponibles en ce qui concerne la plateforme ou les magasins, showroom ou toute entité de distribution, ainsi que contrôler la qualité de notre service.</h5>
            <p>La durée de traitement des données doit être soit celle prévue par la loi ; soit une période de trois ans à compter de la fin de la relation commerciale avec le client ou le prospect ; soit jusqu'à ce que l'objectif applicable à une donnée spécifique cesse d'exister. Par exemple, une donnée relative à vos commandes sera traitée tant que le responsable du traitement pourra avoir besoin de la conserver conformément aux lois en vigueur, puis sera supprimée une fois que cette finalité légitime cessera d'exister.</p>

            <h4>2. Abonnement à la newsletter (dans le cas où cette fonctionnalité serait mise en place à partir de ce site web) et plus généralement envoi d'informations par le biais de l'email.</h4>

            <p>Si vous vous inscrivez à notre service, nous pourrons vous faire parvenir des informations sur nos produits et services via différents supports, tels que par e-mail, par tout autre moyen électronique équivalent (comme les SMS, etc.) ainsi que par « push notifications » via l'application ou la plateforme si vous avez activé ces notifications sur vos appareils de consultation.
                L'inscription à notre service peut entraîner l'utilisation des données personnelles afin de personnaliser la communication liée aux produits et services auxquels vous avez accès par e-mail, par SMS, ou par l'un de nos autres supports électroniques ou de ceux de tiers. Nous pouvons également vous fournir ces informations par « push notifications » depuis l'application ou la plateforme si vous avez activé ces dernières sur vos appareils de consultation. Afin d'améliorer le service que nous vous fournissons, nous vous informons par la présente que les données personnelles liées à vos participations aux jeux édités par la société, vos goûts et préférences, peuvent être utilisées par un service tiers à des fins d'analyse, de création de profils d'utilisateurs, d'études marketing et d'enquêtes qualitatives, ainsi que d'amélioration de nos interactions avec les clients.
                En cas de cookies relatifs à la lettre d'informations, veuillez-vous référer à la politique relative aux cookies pour plus d’informations.
                L'utilisateur est libre de donner son accord à ces fins marketing. En cas de refus de traitement, l'utilisateur ne sera toutefois pas tenu informé de nos nouvelles.
                En cas de refus de profilage des données, nous ne pourrions envoyer à l'utilisateur de la publicité et/ou de manière générale, des documents promotionnels et/ou la lettre d'informations concernant ses propres besoins ou ses préférences. Vous pouvez aussi vous désabonner à tout moment de notre service en suivant les instructions fournies dans chacun de nos messages ou en nous contactant via les informations disponibles dans nos mentions légales.</p>

            <h4>3. Droits relatifs à la protection des données</h4>
            <p>Les responsables du traitement s'engagent à respecter la confidentialité de vos données personnelles et à garantir l'exercice de vos droits. Conformément à la loi française n° 78-17, en date du 6 janvier 1978 modifiée, relative à l'informatique, aux fichiers et aux libertés, et conformément aux disposition de la disposition européenne RGPD du 25 mai 2018 ; vous pouvez exercer vos droits d'accès, de rectification, d'annulation et d'opposition en envoyant un courrier à l'entreprise, en indiquant le motif de votre demande.
                Si vous décidez d'exercer ces droits, et si votre adresse e-mail fait partie des données personnelles que vous avez fournies, nous vous demanderons de nous l'indiquer dans votre demande par écrit, en précisant l'adresse e-mail pour laquelle vous souhaitez exercer vos droits d'accès, de rectification, d'annulation et d'opposition.</p>

            <h4>4. Autres utilisations nécessaires de vos données personnelles</h4>
            <p>Pour atteindre les objectifs indiqués dans cette politique de confidentialité, il peut nous être nécessaire de transmettre ces données personnelles à des sociétés tierces à des fins logistiques, de transport et de livraison, de lutte contre la fraude, statistiques, de confiance, financières, juridiques, judiciaires ou d'analyses marketing. Cette transmission des donnes personnelles exclut la cession ou la vente des données personnelles à des fins commerciales.
                À des fins d'efficacité de service, lesdits partenaires et prestataires peuvent être basés aux États-Unis ou dans d'autres pays ou territoires situés en dehors de l'Espace économique européen qui n'offrent pas le même niveau de protection des données que celui de votre pays ou, le cas échéant, que celui de l'Union européenne.
                En acceptant cette politique de confidentialité et relative aux cookies, vous nous autorisez expressément à traiter et partager vos données personnelles avec les sociétés susmentionnées et/ou à transférer vos données personnelles aux partenaires et prestataires de services correspondants situés en dehors de l'Espace économique européen aux fins décrites dans le présent document. </p>

            <h4>5. Informations sur les cookies</h4>
            <p>Sur cette Plateforme, nous utilisons des cookies qui sont de petits fichiers contenant des informations sur votre navigation sur cette plateforme, dans le seul but d’y faciliter votre navigation. Veuillez lire nos Informations relatives aux cookies pour en savoir plus sur les cookies que nous utilisons, leurs finalités et autres informations importantes.
                Informations relatives aux cookies</p>
            <p>Qu'est-ce qu'un Cookie ?</p>
            <p> Un cookie est un petit fichier de texte qu'un site Internet stocke sur votre PC, votre téléphone ou tout autre dispositif afin de recueillir des données concernant votre navigation sur ce site. Les cookies sont nécessaires pour faciliter la navigation et la rendre plus agréable. Ils ne causent aucun dommage à votre ordinateur.
Bien que la présente politique utilise le terme général de « Cookies » en tant que méthode principale de stockage d'informations utilisée sur ce site Internet, l'espace de « stockage local » du navigateur est également utilisé aux mêmes fins que les Cookies. Toutes les informations contenues dans la présente section s'appliquent également à cet espace de « stockage local ».
                À quelles fins les cookies sont-elles utilisées sur ce site Internet ? Les Cookies sont une partie essentielle du mode de fonctionnement de notre site Internet. Nos cookies ont pour objectif principal d'optimiser votre expérience de navigation. Ils permettent par exemple de retenir vos préférences le cas échéant (langue, pays, etc.) pendant la navigation et lors d'accès ultérieurs.
                Les données recueillies par le biais des Cookies nous permettent d'améliorer notre site, en effectuant des estimations relatives aux nombres et aux modèles d'utilisation, en adaptant le site aux intérêts de chaque utilisateur, en accélérant les recherches, etc.
Nous pouvons occasionnellement, avec votre accord préalable, utiliser des cookies, tags ou autres dispositifs similaires afin d'obtenir des informations nous permettant de vous montrer, soit depuis notre site Internet, ou à partir de sites Internet de tiers ou par tout autre moyen, des annonces publicitaires ciblées en fonction de vos habitudes de navigation.
                À quelles fins les Cookies ne sont-elles pas utilisées sur ce site Internet ? Nous ne stockons pas dans les Cookies que nous utilisons d’informations personnelles sensibles, telles que votre adresse, votre mot de passe, les données de votre carte de crédit ou de débit, etc.
                </p>
                <p>
                Qui utilise les données stockées dans les Cookies ? Les informations stockées dans les Cookies à partir de notre site Internet sont utilisées exclusivement par nos services, à l'exception des cookies appelés ci-après « cookies de tiers », lesquels sont utilisés et gérés par des entités externes afin de nous fournir les services que nous leur avons sollicités dans le but d'améliorer nos prestations et l'expérience de navigation de l'utilisateur. Les « cookies de tiers » ont essentiellement vocation à nous fournir des statistiques d'accès et à garantir les opérations de paiement réalisées.
                Comment éviter l'utilisation de Cookies sur ce site Internet ? Si vous ne souhaitez pas utiliser de cookies sur ce site en tenant compte des limites susmentionnées, vous devez, tout d'abord, désactiver l'utilisation de Cookies dans votre navigateur et ensuite supprimer les Cookies enregistrés sur votre navigateur associé à ce site Internet. Vous pouvez effectuer cette opération à tout moment.
Comment désactiver et empêcher l'utilisation des Cookies ? Vous pouvez restreindre, bloquer ou supprimer les Cookies de ce site Internet à tout moment en modifiant la configuration de votre navigateur comme indiqué ci-après. Puisque les paramètres sont différents d'un navigateur à l'autre, la configuration des Cookies s'effectue habituellement dans les menus « Préférences » ou « Outils ». Pour de plus amples informations sur la configuration des Cookies dans votre navigateur, veuillez consulter le menu « Aide » de ce dernier. Merci de noter que nous ne pouvons pas garantir le bon fonctionnement de la plateforme dans le cas de la désactivation des cookies. </p>    
        
        </div>
    );
}
export default Rgpd;
